name: Update Page

on:
    workflow_dispatch:  
    push:
        branches:
        -   main
    schedule:
    -   cron: '0 0 * * *'
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        
        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
        -    name: Setup Python
             uses: actions/setup-python@v4.7.1
             with:
                python-version: '3.10'
